config/routes.rb
RubyAMFDemo::Application.routes.draw do

  resources :user_sessions

  resources :blogs do
    resources :posts do
      resources :comments
    end
  end

  map_amf :controller => "BlogsController",    :action => "create",  :params => [:blog]
  map_amf :controller => "BlogsController",    :action => "destroy", :params => [:id]
  map_amf :controller => "BlogsController",    :action => "update",  :params => [:blog]
  map_amf :controller => "BlogsController",    :action => "show",    :params => [:id]

  map_amf :posts, :show    => [:id,   :blog_id],
                  :create  => [:post, :blog_id],
                  :update  => [:post, :blog_id],
                  :destroy => [:id,   :blog_id]

  map_amf :comments, :destroy => [:id, :post_id, :blog_id]

end

app/models/blog.rb
class Blog < ActiveRecord::Base

  # RubyAMF in-class mapping
  as_class 'com.rubyamf.demo.models.Blog'

  map_amf :except        => [:byte_content],
          :ignore_fields => [:created_at, :updated_at]

  # Here we use a scope 'show' to return an image and include the posts association. See BlogsController#show. We
  # don't include the image or the posts in the Blog index view, so we do not return them.
  map_amf :show, :methods => :image,
                 :include => :posts,
                 :except  => :byte_content
  
  belongs_to :user
  has_many   :posts, :order => 'created_at DESC',
                     :dependent => :destroy

  # Methods that store and retrieve a ByteArray image in the database 'byte_content' field
  def image
      StringIO.new(self.byte_content) if self.byte_content && !self.byte_content.empty?
  end

  # Sets the value and escapes the string
  def image=(value)
    self.byte_content = value.string if value
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_filter :check_for_live_demo, :only => [:create, :update, :destroy]
  before_filter :require_user, :only => [:new, :edit, :create, :update, :destroy]

  # GET /blogs
  # GET /blogs.xml
  def index
    @blogs = Blog.order('created_at').all

    respond_to do |format|
      format.amf { render :amf => CallResult.new(@blogs) }
      format.html # index.html.erb
      format.xml  { render :xml => @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.xml
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.amf { render :amf => CallResult.new(@blog), :mapping_scope => :show }
      format.html # show.html.erb
      format.xml  { render :xml => @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.xml
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.xml
  def create
     if is_amf?
      @blog = params[:blog]
      current_user.blogs << params[:blog]
    else
      @blog = current_user.blogs.build(params[:blog])
    end

    respond_to do |format|
      if current_user.save
        notice = "Blog was successfully #{action_name}d."
        format.amf  {render :amf => CallResult.new(@blog, notice), :mapping_scope => :show }
        format.html { redirect_to(@blog, :notice => notice) }
        format.xml  { render :xml => @blog, :status => :created, :location => @blog }
      else
        format.amf  {render :amf => FaultObject.new( "Blog was not #{action_name}d.\n" + @blog.full_messages.join(".\n") ) }
        format.html { render :action => "new" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.xml
  def update
    if is_amf?
      # Update and create work the same for amf without scaffolding, which is not used in this example
      create
    else
        @blog = Blog.find(params[:id])
    end

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to(@blog, :notice => 'Blog was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.xml
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.amf  { render :amf => CallResult.new(true,  'Blog deleted!') }
      format.html { redirect_to(blogs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br />
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Tagline</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.tagline %></td>
    <td><%= blog.author %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @blog.title %>
</p>

<p>
  <b>Tagline:</b>
  <%= @blog.tagline %>
</p>

<p>
  <b>Author:</b>
  <%= @blog.author %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>